basePath: /
definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      isEnabled:
        type: boolean
      name:
        type: string
      role:
        $ref: '#/definitions/models.UserRole'
        type: object
      username:
        type: string
      verified:
        type: boolean
    type: object
  models.UserRole:
    properties:
      id:
        type: integer
      isEnabled:
        type: boolean
      name:
        type: string
    type: object
host: http://localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample gin app.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "2.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401": {}
        "403": {}
  /users/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.User'
          type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401": {}
        "403": {}
  /users{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401": {}
        "403": {}
swagger: "2.0"
